# Generated by Django 4.0.1 on 2022-01-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
